### ISSUE TITLE
WinSCP

### ISSUE THREAD

**Issue by hmephi** [Simego-Ltd/datasync-winscp-connector#2]
I need help with WinSCP build from source, Been trying to compile from the source, tried Inno Setup amd Command , still not luck, anyone who can help with  a video showing step by step , Willing to pay 100$ for someone who can help , send me message to hmephi@gmail.com

**Comment by seancleaver** [comment]
To build this connector from the source you need to have installed Data Synchronisation Studio and use Microsoft Visual Studio 2022. It requires downloading the WinSCP nuget package and references to the Data Sync dlls. 

You can also call the build.bat file in the src folder once you have the dependencies and this will use msbuild to compile the code and create a zip file which can be used to install the connector in Data Sync.

**Comment by hmephi** [comment]
Hi Sean

what I am trying to do is to compile from source , see this
https://github.com/winscp/winscp and thare instruction written there but
still fail.

I was to make some changes on WInSCP and compile an executable file but its
not working ..

can you please help with this ? if you have any knowledge .. do you have
direct email i can use to communicate with you

**Comment by seancleaver** [comment]
Ah! OK we haven't built WinSCP from source so couldn't help you. We only take a dependency on the official WinSCP releases of the .NET Framework library via nuget.

**Comment by hmephi** [comment]
Ohk please can you do it for me , and see if it really does work , I need
this urgent and will pay for the work done

**Comment by seancleaver** [comment]
As I said before its not something I can help you with. I do not have the necessary build tool chain requirements for the Official WinSCP project I would suggest that you reach out to the project owners of WinSCP. This project only takes a dependency on the WinSCP .NET Framework Library.
