### ISSUE TITLE
How to install Ouvvi Server

### ISSUE THREAD

**Issue by saiful-islam** [Simego-Ltd/datasync-winscp-connector#3]
Hi, I have installed a new Simego, and Winscp working well. but when deploying it to the Ouvvi server it is not working. 

Showing error: Could not load file or assembly 'Simego.DataSync.Providers.WinSCP' or one of its dependencies. The system cannot find the file specified.

![image](https://github.com/Simego-Ltd/Simego.DataSync.Providers.WinSCP/assets/7437483/16631b4d-15d8-4c57-a2a5-c143f2cf7d5e)

**Comment by seancleaver** [comment]
Have you restarted the Ouvvi Service?

**Comment by saiful-islam** [comment]
No. Should I restart the Ouvvi Server? or From the server which service?

**Comment by seancleaver** [comment]
Just the "Ouvvi Processing Service" from Windows Service Control Manager (services.msc)

**Comment by saiful-islam** [comment]
Now showing different error:
Unable to cast object of type 'Simego.DataSync.Providers.WinSCP.WinSCPDatasourceReader' to type 'Simego.DataSync.Interfaces.IDataSourceReader'.

**Comment by seancleaver** [comment]
Which release are you running DataSync V3/OuvviV4 or DataSync V6/OuvviV6?

**Comment by saiful-islam** [comment]
DataSync V3/OuvviV4

**Comment by seancleaver** [comment]
I've tested with the following configuration which all works from both Data Sync and Ouvvi.

Windows Server 2019
Data Sync - v3.0.2172
Ouvvi - v4.0.2172
WinSCP - Simego.DataSync.Providers.WinSCP v0.0.2
